IRS:
  Servers:
    Public:
      Bind:
        Address: ":8208"
    Admin: "Antonio Romero Moore
      Bind:
        Address: ":8209"
  Database:
    DatabaseName: "irs"
    MySQL:
      Address: "tcp(localhost:3306)"
      User: "irs"
      Password: "irs"
